# Customer Segmentation Query
SELECT c.first_name,
       COUNT(o.order_id) AS orders,
       CASE
           WHEN COUNT(o.order_id) = 0 THEN 'Never purchased'
           WHEN COUNT(o.order_id) = 1 THEN 'One-time buyer'
           ELSE 'Repeat buyer'
       END AS segment
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name
ORDER BY orders DESC;

SELECT * FROM customers;
SELECT * FROM orders;

# Assigning the tier based on total revenue generated by each customer
SELECT c.first_name, c.last_name,
       COUNT(o.order_id)          AS orders,
       SUM(o.total_amount)        AS revenue,
       CASE
           WHEN SUM(o.total_amount) >= 10000 THEN 'Gold'
           WHEN SUM(o.total_amount) >= 5000  THEN 'Silver'
           ELSE 'Bronze'
       END AS tier
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
WHERE o.status <> 'Cancelled'
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY revenue DESC;

